"""deleted sufficeint fields

Revision ID: 1d6006ba399f
Revises: e7a0c8114b19
Create Date: 2025-07-31 12:16:33.234425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6006ba399f'
down_revision: Union[str, Sequence[str], None] = 'e7a0c8114b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'material_qty')
    op.drop_column('buckets', 'material_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('material_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('buckets', sa.Column('material_qty', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
